import { CareerRole, Skill, SkillCategory } from '../types';

export const SKILL_CATEGORIES: { value: SkillCategory; label: string; description: string }[] = [
  { value: 'tech', label: 'Tech & Computing', description: 'Programming, software development, IT' },
  { value: 'business', label: 'Business & Management', description: 'Leadership, strategy, operations' },
  { value: 'law', label: 'Law & Policy', description: 'Legal practice, compliance, policy' },
  { value: 'health', label: 'Medicine & Health', description: 'Clinical practice, healthcare, medical research' },
  { value: 'psychology', label: 'Psychology & Social Sciences', description: 'Mental health, counseling, research' },
  { value: 'arts', label: 'Arts & Humanities', description: 'Creative writing, literature, history' },
  { value: 'design', label: 'Design & Creative', description: 'Visual design, UX/UI, creative direction' },
  { value: 'commerce', label: 'Commerce & Finance', description: 'Accounting, finance, economics' },
  { value: 'stem', label: 'STEM & Research', description: 'Science, engineering, mathematics' },
  { value: 'vocational', label: 'Vocational & Professional', description: 'Trades, technical skills, certifications' },
];

export const ALL_SKILLS: Omit<Skill, 'confidence' | 'interest'>[] = [
  // Tech
  { id: 'js', name: 'JavaScript', category: 'tech' },
  { id: 'python', name: 'Python', category: 'tech' },
  { id: 'java', name: 'Java', category: 'tech' },
  { id: 'react', name: 'React', category: 'tech' },
  { id: 'node', name: 'Node.js', category: 'tech' },
  { id: 'sql', name: 'SQL', category: 'tech' },
  { id: 'aws', name: 'AWS', category: 'tech' },
  { id: 'docker', name: 'Docker', category: 'tech' },
  { id: 'git', name: 'Git', category: 'tech' },
  { id: 'typescript', name: 'TypeScript', category: 'tech' },
  { id: 'html', name: 'HTML/CSS', category: 'tech' },
  { id: 'ml', name: 'Machine Learning', category: 'tech' },
  { id: 'cybersecurity', name: 'Cybersecurity', category: 'tech' },
  { id: 'devops', name: 'DevOps', category: 'tech' },
  { id: 'mobile', name: 'Mobile Development', category: 'tech' },
  
  // Business
  { id: 'leadership', name: 'Leadership', category: 'business' },
  { id: 'strategy', name: 'Strategic Planning', category: 'business' },
  { id: 'project-mgmt', name: 'Project Management', category: 'business' },
  { id: 'negotiation', name: 'Negotiation', category: 'business' },
  { id: 'sales', name: 'Sales', category: 'business' },
  { id: 'marketing', name: 'Marketing', category: 'business' },
  { id: 'analytics', name: 'Business Analytics', category: 'business' },
  { id: 'finance', name: 'Financial Analysis', category: 'business' },
  { id: 'operations', name: 'Operations Management', category: 'business' },
  { id: 'hr', name: 'Human Resources', category: 'business' },
  
  // Law
  { id: 'legal-research', name: 'Legal Research', category: 'law' },
  { id: 'contracts', name: 'Contract Law', category: 'law' },
  { id: 'litigation', name: 'Litigation', category: 'law' },
  { id: 'corporate-law', name: 'Corporate Law', category: 'law' },
  { id: 'criminal-law', name: 'Criminal Law', category: 'law' },
  { id: 'ip-law', name: 'Intellectual Property', category: 'law' },
  { id: 'compliance', name: 'Compliance', category: 'law' },
  { id: 'mediation', name: 'Mediation', category: 'law' },
  
  // Health
  { id: 'patient-care', name: 'Patient Care', category: 'health' },
  { id: 'diagnosis', name: 'Diagnosis', category: 'health' },
  { id: 'surgery', name: 'Surgery', category: 'health' },
  { id: 'pharmacology', name: 'Pharmacology', category: 'health' },
  { id: 'public-health', name: 'Public Health', category: 'health' },
  { id: 'medical-research', name: 'Medical Research', category: 'health' },
  { id: 'nursing', name: 'Nursing', category: 'health' },
  { id: 'radiology', name: 'Radiology', category: 'health' },
  
  // Psychology
  { id: 'counseling', name: 'Counseling', category: 'psychology' },
  { id: 'therapy', name: 'Therapy', category: 'psychology' },
  { id: 'assessment', name: 'Psychological Assessment', category: 'psychology' },
  { id: 'research-methods', name: 'Research Methods', category: 'psychology' },
  { id: 'behavioral-analysis', name: 'Behavioral Analysis', category: 'psychology' },
  { id: 'group-therapy', name: 'Group Therapy', category: 'psychology' },
  
  // Arts
  { id: 'writing', name: 'Creative Writing', category: 'arts' },
  { id: 'literature', name: 'Literature', category: 'arts' },
  { id: 'history', name: 'History', category: 'arts' },
  { id: 'philosophy', name: 'Philosophy', category: 'arts' },
  { id: 'languages', name: 'Languages', category: 'arts' },
  { id: 'journalism', name: 'Journalism', category: 'arts' },
  
  // Design
  { id: 'ui-design', name: 'UI Design', category: 'design' },
  { id: 'ux-design', name: 'UX Design', category: 'design' },
  { id: 'graphic-design', name: 'Graphic Design', category: 'design' },
  { id: 'illustration', name: 'Illustration', category: 'design' },
  { id: 'branding', name: 'Branding', category: 'design' },
  { id: 'photography', name: 'Photography', category: 'design' },
  { id: 'video-editing', name: 'Video Editing', category: 'design' },
  { id: '3d-modeling', name: '3D Modeling', category: 'design' },
  
  // Commerce
  { id: 'accounting', name: 'Accounting', category: 'commerce' },
  { id: 'auditing', name: 'Auditing', category: 'commerce' },
  { id: 'tax', name: 'Tax Planning', category: 'commerce' },
  { id: 'investment', name: 'Investment Analysis', category: 'commerce' },
  { id: 'banking', name: 'Banking', category: 'commerce' },
  { id: 'economics', name: 'Economics', category: 'commerce' },
  { id: 'trading', name: 'Trading', category: 'commerce' },
  
  // STEM
  { id: 'mathematics', name: 'Mathematics', category: 'stem' },
  { id: 'physics', name: 'Physics', category: 'stem' },
  { id: 'chemistry', name: 'Chemistry', category: 'stem' },
  { id: 'biology', name: 'Biology', category: 'stem' },
  { id: 'engineering', name: 'Engineering', category: 'stem' },
  { id: 'data-science', name: 'Data Science', category: 'stem' },
  { id: 'statistics', name: 'Statistics', category: 'stem' },
  { id: 'research', name: 'Research', category: 'stem' },
  
  // Vocational
  { id: 'carpentry', name: 'Carpentry', category: 'vocational' },
  { id: 'plumbing', name: 'Plumbing', category: 'vocational' },
  { id: 'electrical', name: 'Electrical Work', category: 'vocational' },
  { id: 'welding', name: 'Welding', category: 'vocational' },
  { id: 'automotive', name: 'Automotive Repair', category: 'vocational' },
  { id: 'culinary', name: 'Culinary Arts', category: 'vocational' },
];

export const PRIORITY_OPTIONS = [
  'High salary',
  'Work-life balance',
  'Social impact',
  'Creativity',
  'Research',
  'Leadership',
  'Stability',
  'Remote work',
  'Travel',
];

export const TIME_HORIZONS = [
  '<1yr',
  '1-3yrs',
  '3-5yrs',
  '5+yrs',
];

export const CAREER_ROLES: CareerRole[] = [
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    domain: 'Tech & Computing',
    description: 'Design, develop, and maintain software applications and systems. Work with various programming languages and frameworks to build scalable solutions.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'high',
    salaryBand: '$80k - $180k',
    educationIntensity: 'medium',
    typicalIndustries: ['Technology', 'Finance', 'Healthcare', 'E-commerce'],
    requiredSkills: ['js', 'python', 'react', 'node', 'git'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Learn Core Programming', type: 'course', duration: '3 months', effort: 'high', description: 'Complete intensive bootcamp or online courses in JavaScript/Python' },
        { id: '2', title: 'Build Portfolio Projects', type: 'project', duration: '2 months', effort: 'high', description: 'Create 3-5 full-stack applications showcasing your skills' },
        { id: '3', title: 'Contribute to Open Source', type: 'project', duration: '1 month', effort: 'medium', description: 'Contribute to GitHub projects to demonstrate collaboration' },
        { id: '4', title: 'Apply for Junior Positions', type: 'networking', duration: '1 month', effort: 'medium', description: 'Network and apply to entry-level software engineering roles' },
      ],
      budget: [
        { id: '1', title: 'Free Online Courses', type: 'course', duration: '6 months', effort: 'medium', description: 'Complete free courses on freeCodeCamp, Coursera, edX' },
        { id: '2', title: 'Build Personal Projects', type: 'project', duration: '3 months', effort: 'medium', description: 'Create projects using free tools and resources' },
        { id: '3', title: 'Join Developer Communities', type: 'networking', duration: '2 months', effort: 'low', description: 'Participate in online forums and local meetups' },
        { id: '4', title: 'Freelance Projects', type: 'project', duration: '3 months', effort: 'high', description: 'Take on small freelance projects to build experience' },
        { id: '5', title: 'Apply for Entry Roles', type: 'networking', duration: '2 months', effort: 'medium', description: 'Apply to junior positions and internships' },
      ],
      safe: [
        { id: '1', title: 'Computer Science Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete bachelor\'s degree in computer science' },
        { id: '2', title: 'Internships', type: 'internship', duration: '2 summers', effort: 'medium', description: 'Complete summer internships at tech companies' },
        { id: '3', title: 'Build Strong Portfolio', type: 'project', duration: 'Throughout degree', effort: 'medium', description: 'Develop portfolio of projects during studies' },
        { id: '4', title: 'Network with Professionals', type: 'networking', duration: 'Throughout degree', effort: 'low', description: 'Attend career fairs and industry events' },
        { id: '5', title: 'Apply for Graduate Programs', type: 'networking', duration: '6 months', effort: 'medium', description: 'Apply to new graduate programs at top companies' },
      ],
    },
  },
  {
    id: 'product-manager',
    name: 'Product Manager',
    domain: 'Business & Management',
    description: 'Lead product strategy, work with cross-functional teams, and drive product development from conception to launch.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'high',
    salaryBand: '$90k - $200k',
    educationIntensity: 'medium',
    typicalIndustries: ['Technology', 'SaaS', 'E-commerce', 'Fintech'],
    requiredSkills: ['strategy', 'project-mgmt', 'analytics', 'leadership'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Product Management Certification', type: 'certification', duration: '2 months', effort: 'medium', description: 'Complete PM certification (e.g., Google PM Certificate)' },
        { id: '2', title: 'Build Product Portfolio', type: 'project', duration: '3 months', effort: 'high', description: 'Create case studies and product analyses' },
        { id: '3', title: 'Network in PM Community', type: 'networking', duration: '2 months', effort: 'medium', description: 'Join PM meetups and online communities' },
        { id: '4', title: 'Apply for Associate PM Roles', type: 'networking', duration: '1 month', effort: 'medium', description: 'Target entry-level PM positions' },
      ],
      budget: [
        { id: '1', title: 'Free PM Resources', type: 'course', duration: '3 months', effort: 'medium', description: 'Study free PM content and books' },
        { id: '2', title: 'Volunteer for Product Work', type: 'project', duration: '4 months', effort: 'medium', description: 'Volunteer to manage products for non-profits' },
        { id: '3', title: 'Join PM Communities', type: 'networking', duration: 'Ongoing', effort: 'low', description: 'Participate in free PM forums and groups' },
        { id: '4', title: 'Transition from Related Role', type: 'networking', duration: '6 months', effort: 'high', description: 'Move from engineering, design, or business role' },
      ],
      safe: [
        { id: '1', title: 'MBA or Business Degree', type: 'course', duration: '2-4 years', effort: 'high', description: 'Complete MBA or business-related degree' },
        { id: '2', title: 'Start in Related Role', type: 'internship', duration: '1-2 years', effort: 'medium', description: 'Begin as business analyst or project coordinator' },
        { id: '3', title: 'Build PM Skills', type: 'course', duration: 'Throughout', effort: 'medium', description: 'Take PM courses and certifications' },
        { id: '4', title: 'Internal Transition', type: 'networking', duration: '1-2 years', effort: 'medium', description: 'Transition to PM within your company' },
      ],
    },
  },
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    domain: 'STEM & Research',
    description: 'Analyze complex data sets, build predictive models, and provide insights to drive business decisions.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'high',
    salaryBand: '$85k - $170k',
    educationIntensity: 'high',
    typicalIndustries: ['Technology', 'Finance', 'Healthcare', 'Consulting'],
    requiredSkills: ['python', 'ml', 'data-science', 'statistics', 'sql'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Data Science Bootcamp', type: 'course', duration: '3-4 months', effort: 'high', description: 'Complete intensive data science bootcamp' },
        { id: '2', title: 'Kaggle Competitions', type: 'project', duration: '2 months', effort: 'high', description: 'Participate in Kaggle competitions to build portfolio' },
        { id: '3', title: 'Build ML Projects', type: 'project', duration: '2 months', effort: 'high', description: 'Create machine learning projects with real datasets' },
        { id: '4', title: 'Apply for Junior DS Roles', type: 'networking', duration: '1 month', effort: 'medium', description: 'Target entry-level data scientist positions' },
      ],
      budget: [
        { id: '1', title: 'Free Online Courses', type: 'course', duration: '6 months', effort: 'medium', description: 'Complete free courses on Coursera, edX, YouTube' },
        { id: '2', title: 'Practice with Public Datasets', type: 'project', duration: '4 months', effort: 'medium', description: 'Work with free datasets from Kaggle, UCI, etc.' },
        { id: '3', title: 'Join Data Science Communities', type: 'networking', duration: 'Ongoing', effort: 'low', description: 'Participate in online forums and local meetups' },
        { id: '4', title: 'Freelance Data Projects', type: 'project', duration: '3 months', effort: 'high', description: 'Take on freelance data analysis projects' },
      ],
      safe: [
        { id: '1', title: 'Statistics/CS/Math Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete relevant bachelor\'s degree' },
        { id: '2', title: 'Master\'s in Data Science', type: 'course', duration: '2 years', effort: 'high', description: 'Pursue master\'s degree in data science or related field' },
        { id: '3', title: 'Research Projects', type: 'project', duration: 'Throughout', effort: 'medium', description: 'Complete research projects during studies' },
        { id: '4', title: 'Data Analyst Internship', type: 'internship', duration: '1-2 summers', effort: 'medium', description: 'Complete internships in data-related roles' },
        { id: '5', title: 'Apply for Graduate Programs', type: 'networking', duration: '6 months', effort: 'medium', description: 'Target new graduate data scientist programs' },
      ],
    },
  },
  {
    id: 'clinical-psychologist',
    name: 'Clinical Psychologist',
    domain: 'Psychology & Social Sciences',
    description: 'Assess, diagnose, and treat mental health disorders. Provide therapy and counseling to individuals, couples, and groups.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'medium',
    salaryBand: '$70k - $120k',
    educationIntensity: 'high',
    typicalIndustries: ['Healthcare', 'Private Practice', 'Hospitals', 'Schools'],
    requiredSkills: ['counseling', 'therapy', 'assessment', 'research-methods'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Psychology Master\'s', type: 'course', duration: '2 years', effort: 'high', description: 'Complete master\'s in clinical psychology' },
        { id: '2', title: 'Supervised Practice', type: 'internship', duration: '1-2 years', effort: 'high', description: 'Complete required supervised clinical hours' },
        { id: '3', title: 'Licensing Exam', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Prepare for and pass state licensing exam' },
        { id: '4', title: 'Start Practice', type: 'networking', duration: '3 months', effort: 'medium', description: 'Begin private practice or join clinic' },
      ],
      budget: [
        { id: '1', title: 'Psychology Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete bachelor\'s in psychology' },
        { id: '2', title: 'Graduate School (Funding)', type: 'course', duration: '5-6 years', effort: 'high', description: 'Pursue PhD with teaching/research assistantship' },
        { id: '3', title: 'Clinical Internship', type: 'internship', duration: '1 year', effort: 'high', description: 'Complete APA-accredited internship' },
        { id: '4', title: 'Post-Doc Training', type: 'internship', duration: '1-2 years', effort: 'medium', description: 'Complete post-doctoral training if required' },
        { id: '5', title: 'Licensure', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Obtain state license' },
      ],
      safe: [
        { id: '1', title: 'Psychology Bachelor\'s', type: 'course', duration: '4 years', effort: 'high', description: 'Complete bachelor\'s degree in psychology' },
        { id: '2', title: 'Research Experience', type: 'project', duration: '2-3 years', effort: 'medium', description: 'Gain research experience during undergrad' },
        { id: '3', title: 'PhD in Clinical Psychology', type: 'course', duration: '5-7 years', effort: 'high', description: 'Complete APA-accredited PhD program' },
        { id: '4', title: 'Clinical Internship', type: 'internship', duration: '1 year', effort: 'high', description: 'Complete required clinical internship' },
        { id: '5', title: 'Post-Doc & Licensure', type: 'exam_prep', duration: '2 years', effort: 'high', description: 'Complete post-doc and obtain license' },
      ],
    },
  },
  {
    id: 'corporate-lawyer',
    name: 'Corporate Lawyer',
    domain: 'Law & Policy',
    description: 'Advise businesses on legal matters, handle mergers and acquisitions, contracts, compliance, and corporate governance.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'medium',
    salaryBand: '$100k - $300k+',
    educationIntensity: 'high',
    typicalIndustries: ['Law Firms', 'Corporate Legal', 'Finance', 'Consulting'],
    requiredSkills: ['corporate-law', 'contracts', 'legal-research', 'compliance'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Law School (Accelerated)', type: 'course', duration: '2-3 years', effort: 'high', description: 'Complete JD degree (some programs offer accelerated tracks)' },
        { id: '2', title: 'Bar Exam Prep', type: 'exam_prep', duration: '3 months', effort: 'high', description: 'Intensive bar exam preparation' },
        { id: '3', title: 'Pass Bar Exam', type: 'exam_prep', duration: '1 month', effort: 'high', description: 'Pass state bar examination' },
        { id: '4', title: 'Corporate Law Internships', type: 'internship', duration: '2 summers', effort: 'high', description: 'Complete summer associate positions' },
        { id: '5', title: 'Join Corporate Law Firm', type: 'networking', duration: '3 months', effort: 'medium', description: 'Start as associate at law firm' },
      ],
      budget: [
        { id: '1', title: 'Pre-Law Studies', type: 'course', duration: '4 years', effort: 'medium', description: 'Complete bachelor\'s degree (any major)' },
        { id: '2', title: 'LSAT Preparation', type: 'exam_prep', duration: '6-12 months', effort: 'high', description: 'Prepare for and take LSAT exam' },
        { id: '3', title: 'Law School (Scholarships)', type: 'course', duration: '3 years', effort: 'high', description: 'Attend law school with scholarships/grants' },
        { id: '4', title: 'Corporate Law Focus', type: 'course', duration: 'Throughout', effort: 'medium', description: 'Take corporate law courses and join related clubs' },
        { id: '5', title: 'Summer Associateships', type: 'internship', duration: '2 summers', effort: 'high', description: 'Complete summer internships at law firms' },
        { id: '6', title: 'Bar Exam & Licensure', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Pass bar exam and obtain license' },
      ],
      safe: [
        { id: '1', title: 'Strong Undergraduate GPA', type: 'course', duration: '4 years', effort: 'high', description: 'Maintain high GPA in challenging major' },
        { id: '2', title: 'LSAT Excellence', type: 'exam_prep', duration: '12-18 months', effort: 'high', description: 'Achieve top LSAT score for top law schools' },
        { id: '3', title: 'Top Law School', type: 'course', duration: '3 years', effort: 'high', description: 'Attend top-tier law school' },
        { id: '4', title: 'Law Review/Journal', type: 'project', duration: '2 years', effort: 'high', description: 'Join law review or journal' },
        { id: '5', title: 'BigLaw Summer Associate', type: 'internship', duration: '2 summers', effort: 'high', description: 'Complete summer at top law firm' },
        { id: '6', title: 'Bar Exam & BigLaw Associate', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Pass bar and join as associate' },
      ],
    },
  },
  {
    id: 'ux-designer',
    name: 'UX Designer',
    domain: 'Design & Creative',
    description: 'Design user experiences for digital products. Conduct user research, create wireframes, prototypes, and collaborate with developers.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'high',
    salaryBand: '$65k - $140k',
    educationIntensity: 'medium',
    typicalIndustries: ['Technology', 'SaaS', 'E-commerce', 'Agencies'],
    requiredSkills: ['ux-design', 'ui-design', 'research', 'analytics'],
    roadmaps: {
      fast: [
        { id: '1', title: 'UX Design Bootcamp', type: 'course', duration: '3-4 months', effort: 'high', description: 'Complete intensive UX design bootcamp' },
        { id: '2', title: 'Build Design Portfolio', type: 'project', duration: '2 months', effort: 'high', description: 'Create 3-5 case studies showcasing UX process' },
        { id: '3', title: 'Learn Design Tools', type: 'course', duration: '1 month', effort: 'medium', description: 'Master Figma, Sketch, Adobe XD' },
        { id: '4', title: 'Apply for Junior UX Roles', type: 'networking', duration: '1 month', effort: 'medium', description: 'Target entry-level UX positions' },
      ],
      budget: [
        { id: '1', title: 'Free UX Courses', type: 'course', duration: '4 months', effort: 'medium', description: 'Complete free courses on Coursera, YouTube' },
        { id: '2', title: 'Practice with Redesigns', type: 'project', duration: '3 months', effort: 'medium', description: 'Redesign existing apps/websites as practice' },
        { id: '3', title: 'Join Design Communities', type: 'networking', duration: 'Ongoing', effort: 'low', description: 'Participate in Dribbble, Behance, design forums' },
        { id: '4', title: 'Freelance Design Projects', type: 'project', duration: '3 months', effort: 'high', description: 'Take on small freelance UX projects' },
      ],
      safe: [
        { id: '1', title: 'Design Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete bachelor\'s in design, HCI, or related field' },
        { id: '2', title: 'Design Internships', type: 'internship', duration: '2-3 summers', effort: 'medium', description: 'Complete internships at design agencies or tech companies' },
        { id: '3', title: 'Build Portfolio', type: 'project', duration: 'Throughout', effort: 'medium', description: 'Develop strong portfolio during studies' },
        { id: '4', title: 'Network in Design Industry', type: 'networking', duration: 'Throughout', effort: 'low', description: 'Attend design conferences and events' },
        { id: '5', title: 'Apply for Design Roles', type: 'networking', duration: '6 months', effort: 'medium', description: 'Target UX designer positions' },
      ],
    },
  },
  {
    id: 'financial-analyst',
    name: 'Financial Analyst',
    domain: 'Commerce & Finance',
    description: 'Analyze financial data, create models, provide investment recommendations, and support business decision-making.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'medium',
    salaryBand: '$60k - $120k',
    educationIntensity: 'medium',
    typicalIndustries: ['Finance', 'Banking', 'Investment Firms', 'Corporate Finance'],
    requiredSkills: ['finance', 'analytics', 'accounting', 'investment'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Finance Certification', type: 'certification', duration: '3 months', effort: 'high', description: 'Complete CFA Level 1 or FMVA certification' },
        { id: '2', title: 'Build Financial Models', type: 'project', duration: '2 months', effort: 'high', description: 'Create portfolio of financial models and analyses' },
        { id: '3', title: 'Network in Finance', type: 'networking', duration: '2 months', effort: 'medium', description: 'Attend finance meetups and events' },
        { id: '4', title: 'Apply for Analyst Roles', type: 'networking', duration: '1 month', effort: 'medium', description: 'Target entry-level financial analyst positions' },
      ],
      budget: [
        { id: '1', title: 'Free Finance Courses', type: 'course', duration: '4 months', effort: 'medium', description: 'Complete free courses on finance and accounting' },
        { id: '2', title: 'Practice with Public Data', type: 'project', duration: '3 months', effort: 'medium', description: 'Analyze public company financials' },
        { id: '3', title: 'Join Finance Communities', type: 'networking', duration: 'Ongoing', effort: 'low', description: 'Participate in finance forums and groups' },
        { id: '4', title: 'Transition from Related Field', type: 'networking', duration: '6 months', effort: 'high', description: 'Move from accounting, economics, or business role' },
      ],
      safe: [
        { id: '1', title: 'Finance/Economics Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete bachelor\'s in finance, economics, or accounting' },
        { id: '2', title: 'Finance Internships', type: 'internship', duration: '2-3 summers', effort: 'medium', description: 'Complete internships at banks or finance firms' },
        { id: '3', title: 'CFA or MBA', type: 'certification', duration: '2-3 years', effort: 'high', description: 'Pursue CFA designation or MBA' },
        { id: '4', title: 'Network in Finance', type: 'networking', duration: 'Throughout', effort: 'low', description: 'Attend finance career fairs and events' },
        { id: '5', title: 'Apply for Analyst Programs', type: 'networking', duration: '6 months', effort: 'medium', description: 'Target financial analyst programs' },
      ],
    },
  },
  {
    id: 'medical-doctor',
    name: 'Medical Doctor',
    domain: 'Medicine & Health',
    description: 'Diagnose and treat illnesses, perform medical procedures, and provide patient care in various medical specialties.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'medium',
    salaryBand: '$150k - $400k+',
    educationIntensity: 'high',
    typicalIndustries: ['Hospitals', 'Private Practice', 'Clinics', 'Research'],
    requiredSkills: ['patient-care', 'diagnosis', 'medical-research', 'surgery'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Medical School (Accelerated)', type: 'course', duration: '3-4 years', effort: 'high', description: 'Complete medical school (some accelerated programs)' },
        { id: '2', title: 'USMLE Steps', type: 'exam_prep', duration: '2 years', effort: 'high', description: 'Pass USMLE Step 1, 2, and 3' },
        { id: '3', title: 'Residency', type: 'internship', duration: '3-7 years', effort: 'high', description: 'Complete residency program in chosen specialty' },
        { id: '4', title: 'Board Certification', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Obtain board certification in specialty' },
      ],
      budget: [
        { id: '1', title: 'Pre-Med Studies', type: 'course', duration: '4 years', effort: 'high', description: 'Complete bachelor\'s with pre-med requirements' },
        { id: '2', title: 'MCAT Preparation', type: 'exam_prep', duration: '6-12 months', effort: 'high', description: 'Prepare for and take MCAT' },
        { id: '3', title: 'Medical School (Scholarships)', type: 'course', duration: '4 years', effort: 'high', description: 'Attend medical school with scholarships/grants' },
        { id: '4', title: 'USMLE Exams', type: 'exam_prep', duration: '4 years', effort: 'high', description: 'Pass all USMLE steps during medical school' },
        { id: '5', title: 'Residency Match', type: 'internship', duration: '3-7 years', effort: 'high', description: 'Match to residency program' },
        { id: '6', title: 'Board Certification', type: 'exam_prep', duration: '1 year', effort: 'high', description: 'Obtain board certification' },
      ],
      safe: [
        { id: '1', title: 'Strong Pre-Med GPA', type: 'course', duration: '4 years', effort: 'high', description: 'Maintain excellent GPA in challenging pre-med curriculum' },
        { id: '2', title: 'MCAT Excellence', type: 'exam_prep', duration: '12-18 months', effort: 'high', description: 'Achieve top MCAT score' },
        { id: '3', title: 'Top Medical School', type: 'course', duration: '4 years', effort: 'high', description: 'Attend top-tier medical school' },
        { id: '4', title: 'Research & Clinical Experience', type: 'project', duration: 'Throughout', effort: 'high', description: 'Gain research and clinical experience' },
        { id: '5', title: 'USMLE Excellence', type: 'exam_prep', duration: '4 years', effort: 'high', description: 'Excel on all USMLE exams' },
        { id: '6', title: 'Competitive Residency', type: 'internship', duration: '3-7 years', effort: 'high', description: 'Match to competitive residency program' },
        { id: '7', title: 'Board Certification', type: 'exam_prep', duration: '1 year', effort: 'high', description: 'Obtain board certification' },
      ],
    },
  },
  {
    id: 'marketing-manager',
    name: 'Marketing Manager',
    domain: 'Business & Management',
    description: 'Develop and execute marketing strategies, manage campaigns, analyze performance, and drive brand growth.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'medium',
    salaryBand: '$70k - $150k',
    educationIntensity: 'medium',
    typicalIndustries: ['Technology', 'Consumer Goods', 'Agencies', 'E-commerce'],
    requiredSkills: ['marketing', 'analytics', 'strategy', 'project-mgmt'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Digital Marketing Certification', type: 'certification', duration: '2 months', effort: 'medium', description: 'Complete Google Ads, HubSpot, or similar certifications' },
        { id: '2', title: 'Build Marketing Portfolio', type: 'project', duration: '2 months', effort: 'high', description: 'Create case studies of marketing campaigns' },
        { id: '3', title: 'Network in Marketing', type: 'networking', duration: '2 months', effort: 'medium', description: 'Join marketing communities and events' },
        { id: '4', title: 'Apply for Marketing Roles', type: 'networking', duration: '1 month', effort: 'medium', description: 'Target marketing coordinator or specialist roles' },
      ],
      budget: [
        { id: '1', title: 'Free Marketing Courses', type: 'course', duration: '3 months', effort: 'medium', description: 'Complete free courses on digital marketing' },
        { id: '2', title: 'Volunteer Marketing Work', type: 'project', duration: '4 months', effort: 'medium', description: 'Volunteer to manage marketing for non-profits' },
        { id: '3', title: 'Join Marketing Communities', type: 'networking', duration: 'Ongoing', effort: 'low', description: 'Participate in marketing forums and groups' },
        { id: '4', title: 'Transition from Related Role', type: 'networking', duration: '6 months', effort: 'high', description: 'Move from sales, content, or communications role' },
      ],
      safe: [
        { id: '1', title: 'Marketing/Business Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete bachelor\'s in marketing or business' },
        { id: '2', title: 'Marketing Internships', type: 'internship', duration: '2-3 summers', effort: 'medium', description: 'Complete internships at marketing agencies or companies' },
        { id: '3', title: 'Build Marketing Skills', type: 'course', duration: 'Throughout', effort: 'medium', description: 'Take marketing courses and certifications' },
        { id: '4', title: 'Network in Marketing', type: 'networking', duration: 'Throughout', effort: 'low', description: 'Attend marketing conferences and events' },
        { id: '5', title: 'Start as Marketing Coordinator', type: 'networking', duration: '6 months', effort: 'medium', description: 'Begin as coordinator and advance to manager' },
      ],
    },
  },
  {
    id: 'mechanical-engineer',
    name: 'Mechanical Engineer',
    domain: 'STEM & Research',
    description: 'Design, develop, and test mechanical systems and devices. Work on everything from engines to manufacturing equipment.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'medium',
    salaryBand: '$65k - $130k',
    educationIntensity: 'high',
    typicalIndustries: ['Manufacturing', 'Automotive', 'Aerospace', 'Energy'],
    requiredSkills: ['engineering', 'mathematics', 'physics', 'research'],
    roadmaps: {
      fast: [
        { id: '1', title: 'Engineering Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete bachelor\'s in mechanical engineering' },
        { id: '2', title: 'Engineering Internships', type: 'internship', duration: '2-3 summers', effort: 'medium', description: 'Complete internships at engineering firms' },
        { id: '3', title: 'FE Exam', type: 'exam_prep', duration: '3 months', effort: 'high', description: 'Pass Fundamentals of Engineering exam' },
        { id: '4', title: 'Apply for Engineering Roles', type: 'networking', duration: '3 months', effort: 'medium', description: 'Target entry-level mechanical engineer positions' },
      ],
      budget: [
        { id: '1', title: 'Engineering Degree (State School)', type: 'course', duration: '4 years', effort: 'high', description: 'Complete degree at state university' },
        { id: '2', title: 'Co-op Programs', type: 'internship', duration: 'Throughout', effort: 'medium', description: 'Participate in co-op programs for experience' },
        { id: '3', title: 'FE Exam Prep', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Prepare for FE exam with free resources' },
        { id: '4', title: 'Join Engineering Societies', type: 'networking', duration: 'Throughout', effort: 'low', description: 'Join ASME or similar organizations' },
      ],
      safe: [
        { id: '1', title: 'Strong Engineering GPA', type: 'course', duration: '4 years', effort: 'high', description: 'Maintain high GPA in engineering program' },
        { id: '2', title: 'Engineering Internships', type: 'internship', duration: '2-3 summers', effort: 'medium', description: 'Complete internships at top companies' },
        { id: '3', title: 'Research Projects', type: 'project', duration: '2-3 years', effort: 'medium', description: 'Participate in engineering research' },
        { id: '4', title: 'FE & PE Exams', type: 'exam_prep', duration: '2 years', effort: 'high', description: 'Pass FE and eventually PE exams' },
        { id: '5', title: 'Master\'s Degree (Optional)', type: 'course', duration: '2 years', effort: 'high', description: 'Pursue master\'s for advanced roles' },
      ],
    },
  },
];

// Add more careers to reach 50+
const additionalCareers: CareerRole[] = [
  {
    id: 'devops-engineer',
    name: 'DevOps Engineer',
    domain: 'Tech & Computing',
    description: 'Bridge development and operations. Automate infrastructure, manage CI/CD pipelines, and ensure system reliability.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'high',
    salaryBand: '$85k - $160k',
    educationIntensity: 'medium',
    typicalIndustries: ['Technology', 'SaaS', 'E-commerce'],
    requiredSkills: ['devops', 'aws', 'docker', 'git'],
    roadmaps: {
      fast: [
        { id: '1', title: 'DevOps Bootcamp', type: 'course', duration: '3 months', effort: 'high', description: 'Complete DevOps bootcamp' },
        { id: '2', title: 'Cloud Certifications', type: 'certification', duration: '2 months', effort: 'high', description: 'Get AWS/Azure certifications' },
        { id: '3', title: 'Build CI/CD Projects', type: 'project', duration: '2 months', effort: 'high', description: 'Create automation projects' },
        { id: '4', title: 'Apply for DevOps Roles', type: 'networking', duration: '1 month', effort: 'medium', description: 'Target junior DevOps positions' },
      ],
      budget: [
        { id: '1', title: 'Free DevOps Courses', type: 'course', duration: '4 months', effort: 'medium', description: 'Learn from free online resources' },
        { id: '2', title: 'Practice with Free Tier', type: 'project', duration: '3 months', effort: 'medium', description: 'Use free cloud tiers for practice' },
        { id: '3', title: 'Open Source Contributions', type: 'project', duration: '2 months', effort: 'high', description: 'Contribute to DevOps tools' },
      ],
      safe: [
        { id: '1', title: 'CS/IT Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete relevant degree' },
        { id: '2', title: 'System Admin Experience', type: 'internship', duration: '1-2 years', effort: 'medium', description: 'Gain sysadmin experience' },
        { id: '3', title: 'Cloud Certifications', type: 'certification', duration: '1 year', effort: 'high', description: 'Obtain multiple cloud certs' },
      ],
    },
  },
  {
    id: 'nurse-practitioner',
    name: 'Nurse Practitioner',
    domain: 'Medicine & Health',
    description: 'Provide advanced nursing care, diagnose conditions, prescribe medications, and manage patient health.',
    fitScore: 0,
    confidence: 'high',
    growthPotential: 'high',
    salaryBand: '$100k - $150k',
    educationIntensity: 'high',
    typicalIndustries: ['Hospitals', 'Clinics', 'Private Practice'],
    requiredSkills: ['nursing', 'patient-care', 'diagnosis'],
    roadmaps: {
      fast: [
        { id: '1', title: 'BSN Degree', type: 'course', duration: '4 years', effort: 'high', description: 'Complete Bachelor of Science in Nursing' },
        { id: '2', title: 'RN License', type: 'exam_prep', duration: '3 months', effort: 'high', description: 'Pass NCLEX-RN exam' },
        { id: '3', title: 'Nursing Experience', type: 'internship', duration: '1-2 years', effort: 'high', description: 'Work as registered nurse' },
        { id: '4', title: 'NP Master\'s', type: 'course', duration: '2 years', effort: 'high', description: 'Complete NP master\'s program' },
        { id: '5', title: 'NP Certification', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Obtain NP certification' },
      ],
      budget: [
        { id: '1', title: 'ADN or BSN', type: 'course', duration: '2-4 years', effort: 'high', description: 'Complete nursing degree' },
        { id: '2', title: 'RN License', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Pass NCLEX' },
        { id: '3', title: 'Work as RN', type: 'internship', duration: '2-3 years', effort: 'high', description: 'Gain clinical experience' },
        { id: '4', title: 'NP Program (Part-time)', type: 'course', duration: '3 years', effort: 'high', description: 'Complete NP program while working' },
      ],
      safe: [
        { id: '1', title: 'BSN from Top Program', type: 'course', duration: '4 years', effort: 'high', description: 'Complete BSN from accredited program' },
        { id: '2', title: 'RN License', type: 'exam_prep', duration: '3 months', effort: 'high', description: 'Pass NCLEX' },
        { id: '3', title: 'Clinical Experience', type: 'internship', duration: '2-3 years', effort: 'high', description: 'Work in diverse clinical settings' },
        { id: '4', title: 'Top NP Program', type: 'course', duration: '2 years', effort: 'high', description: 'Attend top NP master\'s program' },
        { id: '5', title: 'NP Certification', type: 'exam_prep', duration: '6 months', effort: 'high', description: 'Obtain certification' },
      ],
    },
  },
];

export const ALL_CAREER_ROLES = [...CAREER_ROLES, ...additionalCareers];

// Generate more careers programmatically to reach 50+
const generateMoreCareers = (): CareerRole[] => {
  const templates = [
    { name: 'Cybersecurity Analyst', domain: 'Tech & Computing', skills: ['cybersecurity', 'analytics'], salary: '$75k - $140k' },
    { name: 'Business Analyst', domain: 'Business & Management', skills: ['analytics', 'project-mgmt'], salary: '$60k - $110k' },
    { name: 'Graphic Designer', domain: 'Design & Creative', skills: ['graphic-design', 'branding'], salary: '$45k - $85k' },
    { name: 'Accountant', domain: 'Commerce & Finance', skills: ['accounting', 'tax'], salary: '$50k - $90k' },
    { name: 'Research Scientist', domain: 'STEM & Research', skills: ['research', 'statistics'], salary: '$70k - $130k' },
    { name: 'Social Worker', domain: 'Psychology & Social Sciences', skills: ['counseling', 'therapy'], salary: '$40k - $70k' },
    { name: 'Content Writer', domain: 'Arts & Humanities', skills: ['writing', 'journalism'], salary: '$35k - $75k' },
    { name: 'Civil Engineer', domain: 'STEM & Research', skills: ['engineering', 'mathematics'], salary: '$65k - $120k' },
    { name: 'Pharmacist', domain: 'Medicine & Health', skills: ['pharmacology', 'patient-care'], salary: '$110k - $150k' },
    { name: 'HR Manager', domain: 'Business & Management', skills: ['hr', 'leadership'], salary: '$65k - $120k' },
    { name: 'Architect', domain: 'Design & Creative', skills: ['3d-modeling', 'design'], salary: '$60k - $110k' },
    { name: 'Investment Banker', domain: 'Commerce & Finance', skills: ['investment', 'finance'], salary: '$100k - $300k+' },
    { name: 'Biomedical Engineer', domain: 'STEM & Research', skills: ['engineering', 'biology'], salary: '$70k - $130k' },
    { name: 'Physical Therapist', domain: 'Medicine & Health', skills: ['patient-care', 'therapy'], salary: '$70k - $100k' },
    { name: 'Environmental Scientist', domain: 'STEM & Research', skills: ['research', 'chemistry'], salary: '$50k - $90k' },
    { name: 'Public Relations Manager', domain: 'Business & Management', skills: ['marketing', 'communications'], salary: '$60k - $110k' },
    { name: 'Web Developer', domain: 'Tech & Computing', skills: ['js', 'html', 'react'], salary: '$55k - $120k' },
    { name: 'Dentist', domain: 'Medicine & Health', skills: ['patient-care', 'surgery'], salary: '$120k - $200k' },
    { name: 'Statistician', domain: 'STEM & Research', skills: ['statistics', 'data-science'], salary: '$70k - $130k' },
    { name: 'Operations Manager', domain: 'Business & Management', skills: ['operations', 'leadership'], salary: '$70k - $130k' },
    { name: 'Veterinarian', domain: 'Medicine & Health', skills: ['patient-care', 'diagnosis'], salary: '$80k - $150k' },
    { name: 'Industrial Designer', domain: 'Design & Creative', skills: ['design', '3d-modeling'], salary: '$55k - $100k' },
    { name: 'Economist', domain: 'Commerce & Finance', skills: ['economics', 'research'], salary: '$70k - $140k' },
    { name: 'Chemical Engineer', domain: 'STEM & Research', skills: ['engineering', 'chemistry'], salary: '$70k - $130k' },
    { name: 'Speech Therapist', domain: 'Medicine & Health', skills: ['therapy', 'patient-care'], salary: '$60k - $90k' },
    { name: 'Management Consultant', domain: 'Business & Management', skills: ['strategy', 'analytics'], salary: '$80k - $200k+' },
    { name: 'UI Designer', domain: 'Design & Creative', skills: ['ui-design', 'graphic-design'], salary: '$60k - $120k' },
    { name: 'Actuary', domain: 'Commerce & Finance', skills: ['statistics', 'analytics'], salary: '$70k - $150k' },
    { name: 'Aerospace Engineer', domain: 'STEM & Research', skills: ['engineering', 'physics'], salary: '$80k - $140k' },
    { name: 'Occupational Therapist', domain: 'Medicine & Health', skills: ['therapy', 'patient-care'], salary: '$70k - $100k' },
    { name: 'Supply Chain Manager', domain: 'Business & Management', skills: ['operations', 'analytics'], salary: '$70k - $130k' },
    { name: 'Game Developer', domain: 'Tech & Computing', skills: ['js', 'python', '3d-modeling'], salary: '$60k - $130k' },
    { name: 'Radiologist', domain: 'Medicine & Health', skills: ['radiology', 'diagnosis'], salary: '$300k - $500k+' },
    { name: 'Data Analyst', domain: 'STEM & Research', skills: ['data-science', 'sql', 'analytics'], salary: '$55k - $100k' },
    { name: 'Interior Designer', domain: 'Design & Creative', skills: ['design', '3d-modeling'], salary: '$45k - $85k' },
    { name: 'Auditor', domain: 'Commerce & Finance', skills: ['auditing', 'accounting'], salary: '$55k - $100k' },
    { name: 'Marine Biologist', domain: 'STEM & Research', skills: ['biology', 'research'], salary: '$50k - $90k' },
    { name: 'Event Planner', domain: 'Business & Management', skills: ['project-mgmt', 'marketing'], salary: '$40k - $75k' },
    { name: 'Mobile App Developer', domain: 'Tech & Computing', skills: ['mobile', 'js', 'react'], salary: '$70k - $140k' },
    { name: 'Anesthesiologist', domain: 'Medicine & Health', skills: ['surgery', 'patient-care'], salary: '$300k - $500k+' },
    { name: 'Forensic Scientist', domain: 'STEM & Research', skills: ['chemistry', 'research'], salary: '$50k - $90k' },
    { name: 'Real Estate Agent', domain: 'Business & Management', skills: ['sales', 'negotiation'], salary: '$40k - $150k+' },
  ];

  return templates.map((template, index) => {
    const baseRoadmap = {
      fast: [
        { id: '1', title: 'Education & Training', type: 'course' as const, duration: '2-4 years', effort: 'high' as const, description: 'Complete required education' },
        { id: '2', title: 'Certifications', type: 'certification' as const, duration: '6 months', effort: 'medium' as const, description: 'Obtain relevant certifications' },
        { id: '3', title: 'Entry Position', type: 'networking' as const, duration: '3 months', effort: 'medium' as const, description: 'Apply for entry-level roles' },
      ],
      budget: [
        { id: '1', title: 'Self-Study', type: 'course' as const, duration: '1-2 years', effort: 'medium' as const, description: 'Learn through free resources' },
        { id: '2', title: 'Build Portfolio', type: 'project' as const, duration: '6 months', effort: 'high' as const, description: 'Create work samples' },
        { id: '3', title: 'Network', type: 'networking' as const, duration: '3 months', effort: 'medium' as const, description: 'Connect with professionals' },
      ],
      safe: [
        { id: '1', title: 'Formal Education', type: 'course' as const, duration: '4 years', effort: 'high' as const, description: 'Complete degree program' },
        { id: '2', title: 'Internships', type: 'internship' as const, duration: '2-3 summers', effort: 'medium' as const, description: 'Gain experience' },
        { id: '3', title: 'Professional Network', type: 'networking' as const, duration: 'Throughout', effort: 'low' as const, description: 'Build connections' },
        { id: '4', title: 'Apply for Roles', type: 'networking' as const, duration: '6 months', effort: 'medium' as const, description: 'Target positions' },
      ],
    };

    return {
      id: template.name.toLowerCase().replace(/\s+/g, '-'),
      name: template.name,
      domain: template.domain,
      description: `Professional role in ${template.domain.toLowerCase()}. Requires expertise in ${template.skills.join(', ')}.`,
      fitScore: 0,
      confidence: 'medium' as const,
      growthPotential: 'medium' as const,
      salaryBand: template.salary,
      educationIntensity: 'medium' as const,
      typicalIndustries: ['Various'],
      requiredSkills: template.skills,
      roadmaps: baseRoadmap,
    };
  });
};

export const COMPLETE_CAREER_ROLES = [...ALL_CAREER_ROLES, ...generateMoreCareers()];
